#pragma once

#define CHIP_DEVICE_CONFIG_DEVICE_VENDOR_NAME "Beep Home"
#define CHIP_DEVICE_CONFIG_DEVICE_PRODUCT_NAME "SensAir"
#define CHIP_DEVICE_CONFIG_DEFAULT_DEVICE_HARDWARE_VERSION_STRING "v1.0"
